export const listIntersectionCostant = {
    CREATE_REQUEST: 'INTERSECTION_CREATE_REQUEST',
    CREATE_SUCCESS: 'INTERSECTION_CREATE_SUCCESS',
    CREATE_FAILURE: 'INTERSECTION_CREATE_FAILURE',

    GETSENSORS_REQUEST: 'INTERSECTION_GETELEMENTS_REQUEST',
    GETSENSORS_SUCCESS: 'INTERSECTION_GETELEMENTS_SUCCESS',
    GETSENSORS_FAILURE: 'INTERSECTION_GETELEMENTS_FAILURE',

    UPDATE_REQUEST: 'INTERSECTION_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'INTERSECTION_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'INTERSECTION_UPDATE_FAILURE',

    DELETE_REQUEST: 'INTERSECTION_DELETE_REQUEST',
    DELETE_SUCCESS: 'INTERSECTION_DELETE_SUCCESS',
    DELETE_FAILURE: 'INTERSECTION_DELETE_FAILURE',

    INVALIDATE_INTERSECTION_CACHE: 'INVALIDATE_INTERSECTION_CACHE'
};
