export const listIntersectionConstant = {
    CREATE_REQUEST: 'SENSORS_CREATE_REQUEST',
    CREATE_SUCCESS: 'SENSORS_INTERSECTION_CREATE_SUCCESS',
    CREATE_FAILURE: 'SENSORS_INTERSECTION_CREATE_FAILURE',

    GETSENSORS_REQUEST: 'SENSORS_GETELEMENTS_REQUEST',
    GETSENSORS_SUCCESS: 'SENSORS_GETELEMENTS_SUCCESS',
    GETSENSORS_FAILURE: 'SENSORS_GETELEMENTS_FAILURE',

    UPDATE_REQUEST: 'SENSORS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'SENSORS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'SENSORS_UPDATE_FAILURE',

    DELETE_REQUEST: 'SENSORS_DELETE_REQUEST',
    DELETE_SUCCESS: 'SENSORS_DELETE_SUCCESS',
    DELETE_FAILURE: 'SENSORS_DELETE_FAILURE',



    GETINTERSECTIONS_REQUEST: 'INTERSECTION_GETELEMENTS_REQUEST',
    GETINTERSECTIONS_SUCCESS: 'INTERSECTION_GETELEMENTS_SUCCESS',
    GETINTERSECTIONS_FAILURE: 'INTERSECTION_GETELEMENTS_FAILURE',

    UPDATE_REQUEST_INTERSECTIONS: 'INTERSECTION_UPDATE_REQUEST',
    UPDATE_SUCCESS_INTERSECTIONS: 'INTERSECTION_UPDATE_SUCCESS',
    UPDATE_FAILURE_INTERSECTIONS: 'INTERSECTION_UPDATE_FAILURE',

    DELETE_REQUEST_INTERSECTIONS: 'INTERSECTION_DELETE_REQUEST',
    DELETE_SUCCESS_INTERSECTIONS: 'INTERSECTION_DELETE_SUCCESS',
    DELETE_FAILURE_INTERSECTIONS: 'INTERSECTION_DELETE_FAILURE',
};
