export const queryConstants = {
    CREATE_REQUEST: 'TEAMS_CREATE_REQUEST',
    CREATE_SUCCESS: 'TEAMS_CREATE_SUCCESS',
    CREATE_FAILURE: 'TEAMS_CREATE_FAILURE',

    GETELEMENTS_REQUEST: 'TEAMS_GETELEMENTS_REQUEST',
    GETELEMENTS_SUCCESS: 'TEAMS_GETELEMENTS_SUCCESS',
    GETELEMENTS_FAILURE: 'TEAMS_GETELEMENTS_FAILURE',

    UPDATE_REQUEST: 'TEAMS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'TEAMS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'TEAMS_UPDATE_FAILURE',

    DELETE_REQUEST: 'TEAMS_DELETE_REQUEST',
    DELETE_SUCCESS: 'TEAMS_DELETE_SUCCESS',
    DELETE_FAILURE: 'TEAMS_DELETE_FAILURE',

    INVALIDATE_QUERY_CACHE: 'INVALIDATE_QUERY_CACHE'
};
