export const query2Constants = {
    CREATE_REQUEST: 'QUERY_CREATE_REQUEST',
    CREATE_SUCCESS: 'QUERY_CREATE_SUCCESS',
    CREATE_FAILURE: 'QUERY_CREATE_FAILURE',

    GETELEMENTS_REQUEST: 'QUERY_GETELEMENTS_REQUEST',
    GETELEMENTS_SUCCESS: 'QUERY_GETELEMENTS_SUCCESS',
    GETELEMENTS_FAILURE: 'QUERY_GETELEMENTS_FAILURE',

    UPDATE_REQUEST: 'QUERY_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'QUERY_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'QUERY_UPDATE_FAILURE',

    DELETE_REQUEST: 'QUERY_DELETE_REQUEST',
    DELETE_SUCCESS: 'QUERY_DELETE_SUCCESS',
    DELETE_FAILURE: 'QUERY_DELETE_FAILURE',

    GETELEMENTS1h_REQUEST:'QUERY_CREATE_REQUEST',
    GETELEMENTS1h_FAILURE:'QUERY_CREATE_FAILURE',
    GETELEMENTS1h_SUCCESS: 'QUERY_CREATE_SUCCESS',

    GETELEMENTS24h_REQUEST:'QUERY_CREATE_REQUEST',
    GETELEMENTS24h_SUCCESS: 'QUERY_CREATE_SUCCESS',
    GETELEMENTS_FAILURE24h:'QUERY_CREATE_FAILURE',

    INVALIDATE_QUERY_CACHE: 'INVALIDATE_QUERY_CACHE'
};
