export const query1Constants = {
    CREATE_REQUEST: 'QUERY_CREATE_RANK_REQUEST',
    CREATE_SUCCESS: 'QUERY_CREATE_RANK_SUCCESS',
    CREATE_FAILURE: 'QUERY_CREATE_RANK_FAILURE',

    GETELEMENTS_REQUEST: 'QUERY15_GETELEMENTS_RANK_REQUEST',
    GETELEMENTS_SUCCESS: 'QUERY15_GETELEMENTS_RANK_SUCCESS',
    GETELEMENTS_FAILURE: 'QUERY15_GETELEMENTS_RANK_FAILURE',


    GETELEMENTS1h_REQUEST:'QUERY1_CREATE_RANK_REQUEST',
    GETELEMENTS1h_FAILURE:'QUERY1_CREATE_RANK_FAILURE',
    GETELEMENTS1h_SUCCESS: 'QUERY1_CREATE_RANK_SUCCESS',

    GETELEMENTS24h_REQUEST:'QUERY24_CREATE_RANK_REQUEST',
    GETELEMENTS24h_SUCCESS: 'QUERY24_CREATE_RANK_SUCCESS',
    GETELEMENTS_FAILURE24h:'QUERY24_CREATE_RANK_FAILURE',

};
