export const statisticsConstants = {
    CREATE_REQUEST_TOP1: 'TOP1_CREATE_REQUEST',
    CREATE_SUCCESS_TOP1: 'TOP1_INTERSECTION_CREATE_SUCCESS',
    CREATE_FAILURE_TOP1: 'TOP1_INTERSECTION_CREATE_FAILURE',

    CREATE_REQUEST_TOP2: 'TOP2_CREATE_REQUEST',
    CREATE_SUCCESS_TOP2: 'TOP2_INTERSECTION_CREATE_SUCCESS',
    CREATE_FAILURE_TOP2: 'TOP2_INTERSECTION_CREATE_FAILURE',
};
